import type { AgentDecision, Intent, IntentDraft, Product, Replacement, SelectionMode } from '../types.js';
import { id } from '../utils/crypto.js';
export function parseFixtureDraft(prompt:string,previous?:IntentDraft):IntentDraft { const combined=`${previous?.rawPrompt??''} ${prompt}`.trim();const budget=combined.match(/(?:under|below|maximum|max|₹)\s*₹?\s*([\d,]+)/i); const delivery=combined.match(/(?:within|under)\s*(\d+)\s*days?/i); const size=combined.match(/(UK\s*\d+)/i); const brand=combined.match(/\b(Nike|Adidas|Puma|Asics|Reebok)\b/i);const subscription=/no subscription|without subscription/i.test(combined)?false:/subscription (?:is )?(?:okay|allowed|yes)/i.test(combined)?true:previous?.subscriptionAllowed;const draft:IntentDraft={rawPrompt:combined,category:/shoe/i.test(combined)?'Running shoes':previous?.category,size:size?.[1]?.replace(/\s+/,' ').toUpperCase()??previous?.size,maxAmountPaise:budget?Number(budget[1].replaceAll(',',''))*100:previous?.maxAmountPaise,maxDeliveryDays:delivery?Number(delivery[1]):previous?.maxDeliveryDays,subscriptionAllowed:subscription,brandPreference:brand?.[1]??previous?.brandPreference,ratingPreference:previous?.ratingPreference,warrantyPreference:previous?.warrantyPreference,returnWindowPreference:previous?.returnWindowPreference,missingFields:[]};draft.missingFields=requiredMissing(draft);return draft; }
export function parseFixture(prompt:string): Omit<Intent,'version'|'confirmed'> {const d=parseFixtureDraft(prompt);return {rawPrompt:d.rawPrompt,category:d.category??'',size:d.size,maxAmountPaise:d.maxAmountPaise??0,maxDeliveryDays:d.maxDeliveryDays,subscriptionAllowed:d.subscriptionAllowed??false,brandPreference:d.brandPreference,ratingPreference:d.ratingPreference,warrantyPreference:d.warrantyPreference,returnWindowPreference:d.returnWindowPreference};}
export function requiredMissing(draft:IntentDraft){return [['category',draft.category],['size',draft.size],['maxAmountPaise',draft.maxAmountPaise],['maxDeliveryDays',draft.maxDeliveryDays],['subscriptionAllowed',draft.subscriptionAllowed]].filter(([,value])=>value===undefined||value===null||value==='').map(([field])=>field as string);}
export function fixtureSelect(products:Product[], mode:SelectionMode, scenario:string):AgentDecision { let productId='prod_nike_runner'; if(scenario==='scenario_2' && mode==='NORMAL') productId='prod_premium_x'; const product=products.find(p=>p.id===productId)??products[0]!; return {id:id('decision'),mode,productId:product.id,reason:`${product.name} is a supported choice from the verified offer set.`,claims:[{type:'BUDGET',text:'The product is within the confirmed budget.'}],provider:'fixture',createdAt:new Date().toISOString()}; }

export class FixtureShoppingAiProvider{
  readonly name='fixture';readonly model='fixture-v2';
  async parseIntentDraft(prompt:string,previous?:IntentDraft){return parseFixtureDraft(prompt,previous);}
  async select(intent:Intent,products:Product[],mode:SelectionMode,scenario='scenario_1'){return fixtureSelect(products,mode,scenario);}
  async explainReplacement(_intent:Intent,_replacement:Replacement,product:Product){return `${product.name} still satisfies every confirmed requirement and requires your approval before payment.`;}
}
