export type Decision = 'APPROVE' | 'REVIEW' | 'BLOCK' | 'APPROVE_WITH_OVERRIDE';
export type SelectionMode = 'NORMAL' | 'CLEAN' | 'REPLACEMENT';
export type PermitStatus = 'ISSUED' | 'RESERVED' | 'USED' | 'EXPIRED' | 'BLOCKED' | 'REVOKED';
export interface IntentDraft { rawPrompt: string; category?: string; size?: string; maxAmountPaise?: number; maxDeliveryDays?: number; subscriptionAllowed?: boolean; brandPreference?: string; ratingPreference?: number; warrantyPreference?: number; returnWindowPreference?: number; missingFields: string[]; }
export interface Intent { version: number; rawPrompt: string; category: string; size?: string; maxAmountPaise: number; maxDeliveryDays?: number; subscriptionAllowed: boolean; brandPreference?: string; ratingPreference?: number; warrantyPreference?: number; returnWindowPreference?: number; confirmed: boolean; intentHash?: string; }
export interface Product { id: string; catalogId: string; merchant: string; sku: string; name: string; category: string; brand: string; pricePaise: number; shippingPaise: number; taxPaise: number; stockQuantity: number; deliveryDays: number; subscription: boolean; rating: number; warrantyMonths: number; returnWindowDays: number; availableSizes: string[]; description: string; active: boolean; productVersion: number; }
export interface Cart { merchant: string; sku: string; quantity: number; itemAmountPaise: number; shippingAmountPaise: number; taxAmountPaise: number; addOns: unknown[]; subscription: boolean; amountPaise: number; currency: 'INR'; }
export interface AgentDecision { id: string; mode: SelectionMode; productId: string; reason: string; claims: { type: string; text: string }[]; provider: string; createdAt: string; }
export interface Replacement { productId: string; reasonCodes: string[]; differencesFromOriginal: { amountDifferencePaise: number; deliveryDifferenceDays: number }; }
export interface Evaluation { id: string; sessionId: string; selectedProductId: string; decision: Decision; reasonCodes: string[]; hardRuleResults: { code: string; passed: boolean; message: string }[]; dominance: { productId: string; reasons: string[] }[]; contentRisk: { riskFound: boolean; level: 'NONE'|'LOW'|'HIGH'; categories: string[]; matchedSnippets: string[] }; stability: { normalProductId: string; cleanProductId: string; status: 'STABLE'|'UNSTABLE' }; replacements: Replacement[]; evaluatedCart?: Cart; evaluatedCartHash?: string; createdAt: string; override?: Record<string, unknown>; }
export interface Permit { id: string; sessionId: string; evaluationId: string; intentVersion: number; offerSetHash: string; productId: string; cart: Cart; cartHash: string; nonce: string; signature: string; status: PermitStatus; issuedAt: string; expiresAt: string; createdAt: string; }
export interface Payment { id: string; sessionId?: string; permitId: string; idempotencyKey: string; requestHash?: string; provider: 'mock'|'razorpay'; providerOrderId: string; providerPaymentId?: string; amountPaise: number; currency: 'INR'; status: string; paymentSignatureVerified: boolean; webhookVerified: boolean; failureCode?: string; }
export interface ChatMessage { id: string; clientMessageId?: string; sequence: number; role: 'USER'|'ASSISTANT'|'SYSTEM'; kind: 'TEXT'|'CLARIFYING_QUESTION'|'INTENT_SUMMARY'|'OFFER_SUMMARY'|'RECOMMENDATION'|'DECISION'|'PAYMENT'|'ERROR'; text: string; structuredData?: Record<string, unknown>; createdAt: string; }
export interface AgentToolCall { id: string; sequence: number; toolName: 'read_confirmed_intent'|'search_verified_offers'|'compare_offers'|'submit_candidate'; input: unknown; output: unknown; status: 'COMPLETED'|'FAILED'; createdAt: string; }
export interface AgentRun { id: string; provider: string; model: string; promptVersion: string; status: 'RUNNING'|'COMPLETED'|'FAILED'; toolCalls: AgentToolCall[]; startedAt: string; completedAt?: string; failureCode?: string; }
export interface Receipt { id: string; kind: 'CHOICE_APPROVED'|'CHOICE_BLOCKED'|'PAYMENT_BLOCKED'|'PAYMENT_VERIFIED'; sessionId: string; receiptHash: string; receiptSignature: string; signedAt: string; [key: string]: unknown; }
export interface AuditEntry { id: string; at: string; actor: string; event: string; entityType?: string; entityId?: string; metadata?: Record<string, unknown>; }
export interface OfferSetState { id: string; hash: string; catalogVersion: string; eligible: Product[]; excluded: { product: Product; reason: string }[]; createdAt: string; }
export interface Session { id: string; userId: string; scenarioId: 'scenario_1'|'scenario_2'|'scenario_3'|null; status: string; aiMode: string; paymentMode: string; currentIntentVersion: number; failureCode?: string; intentDraft?: IntentDraft; intent?: Intent; offerSet?: Product[]; offerSetState?: OfferSetState; normal?: AgentDecision; clean?: AgentDecision; evaluation?: Evaluation; permit?: Permit; payments: Payment[]; receipts: Receipt[]; messages: ChatMessage[]; agentRuns: AgentRun[]; audit: AuditEntry[]; createdAt: string; updatedAt: string; }
export interface StoredUser { id: string; email: string; displayName: string; passwordHash: string; }
