export type Decision = 'APPROVE' | 'REVIEW' | 'BLOCK' | 'APPROVE_WITH_OVERRIDE';
export type SelectionMode = 'NORMAL' | 'CLEAN';
export type PermitStatus = 'ISSUED' | 'RESERVED' | 'USED' | 'EXPIRED' | 'BLOCKED' | 'REVOKED';
export interface Intent { version: number; rawPrompt: string; category: string; size?: string; maxAmountPaise: number; maxDeliveryDays?: number; subscriptionAllowed: boolean; brandPreference?: string; ratingPreference?: number; warrantyPreference?: number; confirmed: boolean; }
export interface Product { id: string; catalogId: string; merchant: string; sku: string; name: string; category: string; brand: string; pricePaise: number; shippingPaise: number; taxPaise: number; deliveryDays: number; subscription: boolean; rating: number; warrantyMonths: number; availableSizes: string[]; description: string; active: boolean; }
export interface Cart { merchant: string; sku: string; quantity: number; itemAmountPaise: number; shippingAmountPaise: number; taxAmountPaise: number; addOns: unknown[]; subscription: boolean; amountPaise: number; currency: 'INR'; }
export interface AgentDecision { id: string; mode: SelectionMode; productId: string; reason: string; claims: { type: string; text: string }[]; provider: string; createdAt: string; }
export interface Evaluation { id: string; sessionId: string; selectedProductId: string; decision: Decision; reasonCodes: string[]; hardRuleResults: { code: string; passed: boolean; message: string }[]; dominance: { productId: string; reasons: string[] }[]; contentRisk: { riskFound: boolean; level: 'NONE'|'LOW'|'HIGH'; categories: string[]; matchedSnippets: string[] }; stability: { normalProductId: string; cleanProductId: string; status: 'STABLE'|'UNSTABLE' }; createdAt: string; override?: Record<string, unknown>; }
export interface Permit { id: string; sessionId: string; evaluationId: string; productId: string; cart: Cart; cartHash: string; nonce: string; signature: string; status: PermitStatus; expiresAt: string; createdAt: string; }
export interface Payment { id: string; permitId: string; idempotencyKey: string; provider: 'mock'|'razorpay'; providerOrderId: string; amountPaise: number; currency: 'INR'; status: string; paymentSignatureVerified: boolean; webhookVerified: boolean; }
export interface Session { id: string; userId: string; scenarioId: 'scenario_1'|'scenario_2'|'scenario_3'; status: string; intent?: Intent; offerSet?: Product[]; normal?: AgentDecision; clean?: AgentDecision; evaluation?: Evaluation; permit?: Permit; payments: Payment[]; audit: { at: string; actor: string; event: string; metadata?: Record<string, unknown> }[]; }
