import request from 'supertest';
import { beforeAll, describe, expect, it } from 'vitest';
import { createApp } from '../../src/app.js';

const app=createApp();
let auth:Record<string,string>;
beforeAll(async()=>{const response=await request(app).post('/api/v1/auth/demo-login').send({email:'demo@choiceproof.local',password:'choiceproof-demo'});auth={Authorization:`Bearer ${response.body.data.accessToken}`};});

async function createSession(scenarioId:'scenario_1'|'scenario_2'|'scenario_3'|null=null){return (await request(app).post('/api/v1/sessions').set(auth).send({scenarioId})).body.data;}
async function confirmed(scenarioId:'scenario_1'|'scenario_2'|'scenario_3'='scenario_1'){const session=await createSession(scenarioId);await request(app).post(`/api/v1/sessions/${session.id}/intent/parse`).set(auth).send({prompt:'Buy Nike running shoes, size UK 8, under ₹5,000, delivery within 4 days, and no subscription.'});await request(app).post(`/api/v1/sessions/${session.id}/intent/confirm`).set(auth).send({});return session;}

describe('ChoiceProof Concierge',()=>{
  it('collects missing requirements through persistent guided messages',async()=>{const session=await createSession();const firstId=crypto.randomUUID();const first=await request(app).post(`/api/v1/sessions/${session.id}/messages`).set(auth).send({message:'I need Nike running shoes under ₹5,000.',clientMessageId:firstId});expect(first.status).toBe(201);expect(first.body.data.actionRequired).toBe('ANSWER_QUESTION');expect(first.body.data.missingFields).toContain('size');const repeated=await request(app).post(`/api/v1/sessions/${session.id}/messages`).set(auth).send({message:'ignored duplicate',clientMessageId:firstId});expect(repeated.body.data.userMessage.id).toBe(first.body.data.userMessage.id);const second=await request(app).post(`/api/v1/sessions/${session.id}/messages`).set(auth).send({message:'UK 8, delivered within 4 days, and no subscription.',clientMessageId:crypto.randomUUID()});expect(second.body.data.actionRequired).toBe('CONFIRM_INTENT');const confirm=await request(app).post(`/api/v1/sessions/${session.id}/intent/confirm`).set(auth).send({});expect(confirm.status).toBe(200);expect(confirm.body.data.confirmed).toBe(true);});

  it('runs a bounded agent and records its safe tool trace',async()=>{const session=await confirmed();const result=await request(app).post(`/api/v1/sessions/${session.id}/agent/run`).set(auth);expect(result.status).toBe(200);expect(result.body.data.evaluation.decision).toBe('APPROVE');const view=await request(app).get(`/api/v1/sessions/${session.id}/view`).set(auth);expect(view.body.data.agentRuns[0].toolCalls.map((x:{toolName:string})=>x.toolName)).toEqual(['read_confirmed_intent','search_verified_offers','compare_offers','submit_candidate','submit_candidate']);expect(view.body.data.allowedNextActions).toContain('ISSUE_PERMIT');});

  it('returns and applies a general safe replacement after review',async()=>{const session=await confirmed('scenario_2');const run=await request(app).post(`/api/v1/sessions/${session.id}/agent/run`).set(auth);expect(run.body.data.evaluation.decision).toBe('REVIEW');const evaluation=run.body.data.evaluation;expect(evaluation.replacements.length).toBeGreaterThan(0);const chosen=evaluation.replacements[0].productId;const result=await request(app).post(`/api/v1/evaluations/${evaluation.id}/review`).set(auth).send({action:'CHOOSE_REPLACEMENT',productId:chosen});expect(result.status).toBe(200);expect(result.body.data.selectedProductId).toBe(chosen);expect(result.body.data.decision).toBe('APPROVE');});

  it('detects idempotency conflicts and verifies a persisted receipt',async()=>{const session=await confirmed();const run=(await request(app).post(`/api/v1/sessions/${session.id}/agent/run`).set(auth)).body.data;const permit=(await request(app).post(`/api/v1/evaluations/${run.evaluation.id}/permit`).set(auth)).body.data;const key=crypto.randomUUID();const order=await request(app).post(`/api/v1/permits/${permit.id}/create-order`).set(auth).send({idempotencyKey:key,candidateCart:permit.cart});expect(order.status).toBe(200);const conflict=await request(app).post(`/api/v1/permits/${permit.id}/create-order`).set(auth).send({idempotencyKey:key,candidateCart:{...permit.cart,amountPaise:permit.cart.amountPaise+100}});expect(conflict.status).toBe(409);expect(conflict.body.error.code).toBe('IDEMPOTENCY_CONFLICT');const captured=await request(app).post('/api/v1/payments/mock-complete').set(auth).send({providerOrderId:order.body.data.providerOrderId});const receipt=captured.body.data.receipt;const verification=await request(app).post('/api/v1/receipts/verify').set(auth).send(receipt);expect(verification.body.data.valid).toBe(true);const tampered=await request(app).post('/api/v1/receipts/verify').set(auth).send({...receipt,kind:'PAYMENT_BLOCKED'});expect(tampered.body.data.valid).toBe(false);});
});
