import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { createApp } from '../../src/app.js';

const app=createApp();
async function token(){const r=await request(app).post('/api/v1/auth/demo-login').send({email:'demo@choiceproof.local',password:'choiceproof-demo'});return r.body.data.accessToken as string;}
async function ready(scenario:'scenario_1'|'scenario_2'|'scenario_3'){const t=await token();const h={Authorization:`Bearer ${t}`};const session=(await request(app).post('/api/v1/sessions').set(h).send({scenarioId:scenario})).body.data;await request(app).post(`/api/v1/sessions/${session.id}/intent/parse`).set(h).send({prompt:'Buy Nike running shoes, size UK 8, under ₹5,000, delivery within 4 days, and no subscription.'});await request(app).post(`/api/v1/sessions/${session.id}/intent/confirm`).set(h).send({});await request(app).get(`/api/v1/sessions/${session.id}/catalog`).set(h);await request(app).post(`/api/v1/sessions/${session.id}/agent/select`).set(h);return {t,h,session};}
describe('ChoiceProof demo flow',()=>{it('approves clean selection',async()=>{const x=await ready('scenario_1');const r=await request(app).post(`/api/v1/sessions/${x.session.id}/evaluate`).set(x.h);expect(r.body.data.decision).toBe('APPROVE');});it('reviews unstable selection',async()=>{const x=await ready('scenario_2');const r=await request(app).post(`/api/v1/sessions/${x.session.id}/evaluate`).set(x.h);expect(r.body.data.decision).toBe('REVIEW');expect(r.body.data.reasonCodes).toContain('SELECTION_UNSTABLE');});it('blocks a mutated cart before order creation',async()=>{const x=await ready('scenario_3');const evaluation=(await request(app).post(`/api/v1/sessions/${x.session.id}/evaluate`).set(x.h)).body.data;const permit=(await request(app).post(`/api/v1/evaluations/${evaluation.id}/permit`).set(x.h)).body.data;const r=await request(app).post(`/api/v1/permits/${permit.id}/create-order`).set(x.h).send({idempotencyKey:'efc5810b-a7ff-4c9c-a806-a993e5fb9c44',candidateCart:{merchant:'DemoSports',sku:'PREMIUM-X-01',quantity:1,itemAmountPaise:649900,shippingAmountPaise:0,taxAmountPaise:0,addOns:[],subscription:false,amountPaise:649900,currency:'INR'}});expect(r.status).toBe(409);expect(r.body.data.razorpayOrderCreated).toBe(false);});
it('captures a mock payment after an exact-cart order',async()=>{const x=await ready('scenario_1');const evaluation=(await request(app).post(`/api/v1/sessions/${x.session.id}/evaluate`).set(x.h)).body.data;const permit=(await request(app).post(`/api/v1/evaluations/${evaluation.id}/permit`).set(x.h)).body.data;const order=(await request(app).post(`/api/v1/permits/${permit.id}/create-order`).set(x.h).send({idempotencyKey:'3f1c9a20-6d4b-4c8e-9a11-2b7e0d41a901',candidateCart:permit.cart})).body.data;const captured=await request(app).post('/api/v1/payments/mock-complete').set(x.h).send({providerOrderId:order.providerOrderId});expect(captured.status).toBe(200);expect(captured.body.data.payment.status).toBe('CAPTURED');expect(captured.body.data.receipt.receiptSignature).toBeTruthy();});});
